import type { Product, Category } from "@/types/product";

export const MOCK_CATEGORIES: Category[] = [
  {
    id: "cat_1",
    name: "Fresh Produce",
    slug: "fresh-produce",
    description: "Farm fresh fruits and vegetables",
    imageUrl: "/placeholder-category.jpg",
    parentId: null,
    displayOrder: 1,
    isActive: true,
    metaTitle: null,
    metaDescription: null,
  },
  {
    id: "cat_2",
    name: "Dairy & Bakery",
    slug: "dairy-bakery",
    description: "Daily essentials like milk, bread, and eggs",
    imageUrl: "/placeholder-category.jpg",
    parentId: null,
    displayOrder: 2,
    isActive: true,
    metaTitle: null,
    metaDescription: null,
  },
  {
    id: "cat_3",
    name: "Pantry Staples",
    slug: "pantry-staples",
    description: "Rice, dal, spices, and cooking oil",
    imageUrl: "/placeholder-category.jpg",
    parentId: null,
    displayOrder: 3,
    isActive: true,
    metaTitle: null,
    metaDescription: null,
  },
  {
    id: "cat_4",
    name: "Snacks & Beverages",
    slug: "snacks-beverages",
    description: "Chips, biscuits, tea, and coffee",
    imageUrl: "/placeholder-category.jpg",
    parentId: null,
    displayOrder: 4,
    isActive: true,
    metaTitle: null,
    metaDescription: null,
  },
  {
    id: "cat_5",
    name: "Personal Care",
    slug: "personal-care",
    description: "Soaps, shampoos, and oral care",
    imageUrl: "/placeholder-category.jpg",
    parentId: null,
    displayOrder: 5,
    isActive: true,
    metaTitle: null,
    metaDescription: null,
  },
  {
    id: "cat_6",
    name: "Home Cleaning",
    slug: "home-cleaning",
    description: "Detergents and cleaning supplies",
    imageUrl: "/placeholder-category.jpg",
    parentId: null,
    displayOrder: 6,
    isActive: true,
    metaTitle: null,
    metaDescription: null,
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "prod_1",
    name: "Organic Toor Dal (Pigeon Pea)",
    slug: "organic-toor-dal",
    sku: "DAL-TOOR-001",
    description: "High-quality, unpolished organic toor dal sourced directly from farmers.",
    shortDescription: "Unpolished organic toor dal.",
    brand: "Pearl Naturals",
    unit: "kg",
    basePrice: 18000, // ₹180.00
    salePrice: 16500, // ₹165.00
    costPrice: 12000,
    taxRate: 5,
    images: [{ url: "/placeholder-product.jpg", alt: "Toor Dal", position: 1 }],
    tags: ["organic", "dal", "pantry"],
    attributes: { Origin: "Maharashtra", Quality: "Unpolished" },
    isActive: true,
    isFeatured: true,
    categoryId: "cat_3",
    viewCount: 1250,
    metaTitle: null,
    metaDescription: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    inventory: {
      quantityOnHand: 50,
      quantityReserved: 5,
      quantityAvailable: 45,
      lowStockThreshold: 10,
      reorderPoint: 20,
      maxCapacity: 100,
      allowBackorder: false,
      lastCountedAt: new Date().toISOString(),
    },
  },
  {
    id: "prod_2",
    name: "Farm Fresh Tomatoes",
    slug: "farm-fresh-tomatoes",
    sku: "VEG-TOM-001",
    description: "Locally grown, ripe and juicy tomatoes perfect for cooking and salads.",
    shortDescription: "Fresh local tomatoes.",
    brand: "Local Farms",
    unit: "kg",
    basePrice: 4000, // ₹40.00
    salePrice: null,
    costPrice: 2500,
    taxRate: 0,
    images: [{ url: "/placeholder-product.jpg", alt: "Tomatoes", position: 1 }],
    tags: ["fresh", "vegetable"],
    attributes: { Type: "Hybrid", Origin: "Local" },
    isActive: true,
    isFeatured: true,
    categoryId: "cat_1",
    viewCount: 890,
    metaTitle: null,
    metaDescription: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    inventory: {
      quantityOnHand: 20,
      quantityReserved: 0,
      quantityAvailable: 20,
      lowStockThreshold: 5,
      reorderPoint: 10,
      maxCapacity: 50,
      allowBackorder: false,
      lastCountedAt: new Date().toISOString(),
    },
  },
  {
    id: "prod_3",
    name: "Pure Cow Ghee",
    slug: "pure-cow-ghee",
    sku: "DRY-GHEE-001",
    description: "Traditional bilona churned pure cow ghee with rich aroma and taste.",
    shortDescription: "Traditional pure cow ghee.",
    brand: "Pearl Dairy",
    unit: "500ml",
    basePrice: 35000, // ₹350.00
    salePrice: null,
    costPrice: 28000,
    taxRate: 12,
    images: [{ url: "/placeholder-product.jpg", alt: "Cow Ghee", position: 1 }],
    tags: ["dairy", "ghee", "premium"],
    attributes: { Method: "Bilona Churned" },
    isActive: true,
    isFeatured: false,
    categoryId: "cat_2",
    viewCount: 2100,
    metaTitle: null,
    metaDescription: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    inventory: {
      quantityOnHand: 15,
      quantityReserved: 2,
      quantityAvailable: 13,
      lowStockThreshold: 5,
      reorderPoint: 10,
      maxCapacity: 30,
      allowBackorder: true,
      lastCountedAt: new Date().toISOString(),
    },
  },
  {
    id: "prod_4",
    name: "Whole Wheat Atta",
    slug: "whole-wheat-atta",
    sku: "PAN-ATTA-001",
    description: "Stone ground whole wheat chakki atta for soft and fluffy rotis.",
    shortDescription: "Stone ground wheat flour.",
    brand: "Pearl Naturals",
    unit: "5kg",
    basePrice: 25000, // ₹250.00
    salePrice: 22500, // ₹225.00
    costPrice: 19000,
    taxRate: 5,
    images: [{ url: "/placeholder-product.jpg", alt: "Wheat Atta", position: 1 }],
    tags: ["pantry", "flour"],
    attributes: { Type: "Stone Ground" },
    isActive: true,
    isFeatured: true,
    categoryId: "cat_3",
    viewCount: 3400,
    metaTitle: null,
    metaDescription: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    inventory: {
      quantityOnHand: 0,
      quantityReserved: 0,
      quantityAvailable: 0,
      lowStockThreshold: 10,
      reorderPoint: 20,
      maxCapacity: 100,
      allowBackorder: false,
      lastCountedAt: new Date().toISOString(),
    },
  },
];
